### ISSUE TITLE
Consistent Friends/Followers logic

### ISSUE THREAD

**Issue by xkb** [CMPUT404/socialdistribution#193]
This is what I'm currently doing on the front with respect to each call.
#### `POST /friendrequest`

Add `friend` to `following`
if `friend` in `requests` remove and add to `friends`
else add to `pending`
#### `GET /author/:id/follow/:id`

Add `friend` to `following`
#### `DELETE /author/:id/follow/:id`

remove `friend` from `friends`, `pending` and `following`

This is probably not all alright but lets all agree what needs to happen on each call in both ends.

**Comment by mraypold** [comment]
The `POST /friendrequest` logics looks correct according to my understanding.

The `GET /author/:id/follow/:id` logic is fine.

`DELETE /author/:id/follow/:id` needs to be modified as it hasn't been updated to take into account the pending list yet. Now is the time to suggest an alternative logic.

We can handle unfriending and unfollowing in separate endpoints if it makes more sense to you, so that you can unfriend someone, but not stop following. Perhaps DELETE /author/:id/unfriend/:id which removes friends, and pending, but leaves intact following.

**Comment by xkb** [comment]
I'm okay with leaving the unfollow request serving the purpose of unfollowing **and** unfriending as long as it happens the same way in the backend.

If it's easier to split into two then a `DELETE /author/:id/friend/:id` is fine.

@derekdowling

**Comment by xkb** [comment]
cb2c6d4318ffee3a080da26bc28da548d0ed8311

**Comment by xkb** [comment]
Reopening since this is still messed up. @mraypold is fixing it.

**Comment by xkb** [comment]
### Still needs work
- ~~A follows B, B follows A => A & B become friends
  `FollowRequestSerializer` should probably return a boolean from follow/_add_follower indicating whether the relationship was promoted.~~
- [CreateFriendRequest](https://github.com/CMPUT404/socialdistribution/blob/master/api/views/author.py#L129) needs a `author.add_request` to add friend requests from external hosts
- Remote calls

**Comment by derekdowling** [comment]
@KarimBaaba if you mean: `A friends B, B friends A => A & B become friends` then I agree. Otherwise, following is independent of the becoming friends process as outlined [here](https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=484561).

**Comment by xkb** [comment]
Crap, I keep forgetting :sleeping:

**Comment by xkb** [comment]
@derekdowling: that part is actually done.
