### ISSUE TITLE
As an author, I want to befriend remote authors

### ISSUE THREAD

**Issue by jcairo** [CMPUT404/socialdistribution#44]

**Comment by derekdowling** [comment]
This is going to need coordination probably between @KarimBaaba and @mraypold on how we want to do this. Perhaps the simplest way is proxy through the backend so that it can add state to the request such as "PENDING" or "FRIENDS" for determining what results from the friend request when the remote server responds to the request. It might be a bit slower, but it will be far simpler to test.

**Comment by derekdowling** [comment]
Logic is there, just need to confirm that it works with the integrator, testable, and hardened.

**Comment by derekdowling** [comment]
This is done and working as far as I can tell.
